# This workflow will bump the patch version of the package and create a release on GitHub.
# It triggers the npm-publish workflow to publish the package to NPM.

name: Auto Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_PUSH_TOKEN }}

      - name: 'Configure git'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Bump patch version
        run: npm version patch

      - name: Get version
        id: project-version
        uses: 'euberdeveloper/ga-project-version@main'
        with:
          package-manager: 'npm'

      - run: git push

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.REPO_PUSH_TOKEN }}"
          automatic_release_tag: "v${{ steps.project-version.outputs.version }}"
          prerelease: false
          title: "v${{ steps.project-version.outputs.version }}"

